import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00193 :
    checkEncoded [[1], [-1, 2, 1]]
      [10, 14, 14, 14, 14, 14, 14, 215, 11, 208, 30, 5, 196, 151, 96, 95, 152, 195, 4, 29, 207, 10, 216, 15, 15, 16, 18, 15, 15, 14, 14, 14, 137, 12, 200, 195, 196, 199, 13, 138, 18, 18, 15, 14, 14, 67, 44, 183, 152, 184, 152, 179, 17, 164, 149, 165, 149, 166, 41, 54, 16, 14, 14, 14, 14, 14, 230, 18, 213, 15, 15, 15, 17, 14, 14, 14, 14, 156, 195, 83, 197, 29, 212, 18, 195, 30, 182, 70, 180, 153, 19, 15, 17, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00193_solvable : EncodedStableSolvable [[1], [-1, 2, 1]] :=
  checkEncoded_sound gen_gen_20260913_00193

#print axioms gen_gen_20260913_00193_solvable
