import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00300 :
    checkEncoded [[2, -1], [-1, -1, -1, 2, 1, 1, 1]]
      [7, 8, 10, 7, 0, 10, 2, 10, 14, 14, 14, 14, 183, 67, 100, 16, 83, 54, 166, 17, 15, 17, 14, 14, 13, 151, 11, 7, 6, 10, 152, 12, 18, 16, 14, 14, 14, 14, 14, 14, 255, 116, 150, 172, 171, 149, 115, 256, 15, 17, 18, 17, 15, 16, 14, 14, 5, 54, 163, 70, 32, 184, 71, 151, 168, 0, 0, 167, 152, 72, 183, 31, 69, 164, 53, 4, 15, 15, 14, 14, 14, 9, 183, 83, 87, 154, 153, 88, 84, 184, 8, 15, 17, 17, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00300_solvable : EncodedStableSolvable [[2, -1], [-1, -1, -1, 2, 1, 1, 1]] :=
  checkEncoded_sound gen_gen_20260913_00300

#print axioms gen_gen_20260913_00300_solvable
