import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00041 :
    checkEncoded [[-1, -2, 1, 2, 1], [2, 1]]
      [5, 6, 8, 10, 14, 14, 14, 14, 14, 202, 81, 75, 3, 17, 2, 60, 68, 183, 18, 15, 15, 16, 14, 56, 15, 4, 14, 14, 0, 178, 32, 180, 168, 54, 140, 139, 53, 167, 179, 31, 177, 0, 17, 17, 14, 14, 14, 14, 14, 14, 182, 177, 237, 3, 245, 126, 125, 246, 2, 238, 178, 181, 15, 20, 18, 18, 16, 15, 14, 14, 14, 14, 14, 14, 247, 203, 209, 154, 212, 212, 17, 195, 195, 151, 194, 186, 230, 16, 15, 18, 18, 16, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00041_solvable : EncodedStableSolvable [[-1, -2, 1, 2, 1], [2, 1]] :=
  checkEncoded_sound gen_gen_20260913_00041

#print axioms gen_gen_20260913_00041_solvable
