import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00376 :
    checkEncoded [[-1, -1, -1, -2, 1], [2, 2, 1, -2]]
      [6, 13, 2, 13, 12, 0, 7, 5, 13, 14, 14, 14, 14, 5, 29, 1, 86, 196, 59, 137, 184, 183, 138, 60, 195, 85, 1, 30, 4, 20, 19, 16, 17, 14, 14, 14, 14, 54, 142, 100, 166, 154, 1, 83, 18, 70, 1, 151, 165, 85, 139, 53, 17, 17, 16, 14, 14, 14, 14, 14, 14, 210, 139, 82, 253, 173, 209, 172, 181, 16, 164, 153, 194, 156, 236, 67, 138, 193, 18, 17, 16, 17, 16, 14, 14, 14, 14, 14, 14, 105, 39, 40, 106, 18, 15, 18, 16, 17, 15, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00376_solvable : EncodedStableSolvable [[-1, -1, -1, -2, 1], [2, 2, 1, -2]] :=
  checkEncoded_sound gen_gen_20260913_00376

#print axioms gen_gen_20260913_00376_solvable
