import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00229 :
    checkEncoded [[1], [1, 2, -1]]
      [11, 14, 14, 14, 14, 14, 14, 36, 129, 55, 111, 224, 56, 246, 64, 19, 61, 229, 55, 205, 98, 56, 116, 33, 21, 17, 16, 18, 15, 14, 14, 14, 14, 14, 14, 74, 115, 112, 112, 78, 256, 15, 237, 61, 95, 95, 100, 57, 18, 18, 15, 17, 15, 14, 14, 14, 142, 141, 15, 16, 15, 14, 150, 149, 0, 29, 165, 166, 30, 0, 150, 149, 15, 14, 14, 14, 1, 141, 198, 3, 138, 150, 154, 149, 18, 150, 151, 149, 137, 2, 181, 140, 1, 15, 15, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00229_solvable : EncodedStableSolvable [[1], [1, 2, -1]] :=
  checkEncoded_sound gen_gen_20260913_00229

#print axioms gen_gen_20260913_00229_solvable
