import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00061 :
    checkEncoded [[2, 2, 1, -2], [-1, 2, 2, -1, -2, -2, 1]]
      [10, 13, 9, 4, 9, 3, 12, 7, 10, 2, 8, 11, 0, 7, 6, 0, 10, 9, 3, 11, 14, 14, 14, 2, 56, 153, 72, 168, 165, 166, 167, 71, 154, 55, 3, 17, 17, 15, 14, 14, 14, 14, 14, 14, 144, 98, 216, 130, 4, 95, 156, 30, 21, 29, 155, 96, 5, 115, 215, 97, 143, 17, 20, 18, 18, 15, 11, 10, 13, 11, 7, 7, 1, 1, 6, 6, 10, 12, 11, 10, 14, 23, 162, 161, 138, 7, 16, 6, 8, 11, 10, 1, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00061_solvable : EncodedStableSolvable [[2, 2, 1, -2], [-1, 2, 2, -1, -2, -2, 1]] :=
  checkEncoded_sound gen_gen_20260913_00061

#print axioms gen_gen_20260913_00061_solvable
