import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00159 :
    checkEncoded [[2, 1, -2, -2], [2]]
      [13, 9, 2, 14, 14, 14, 14, 14, 14, 153, 61, 158, 189, 84, 46, 22, 45, 83, 190, 157, 62, 154, 16, 17, 16, 16, 17, 14, 14, 14, 186, 202, 24, 56, 195, 149, 15, 9, 178, 4, 23, 183, 167, 18, 16, 14, 14, 14, 14, 14, 14, 252, 19, 233, 20, 15, 17, 17, 16, 14, 14, 14, 14, 14, 14, 171, 219, 252, 161, 197, 87, 16, 72, 180, 11, 233, 202, 154, 17, 20, 18, 18, 15, 14, 14, 14, 14, 14, 14, 204, 213, 16, 196, 185, 17, 15, 17, 15, 17, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00159_solvable : EncodedStableSolvable [[2, 1, -2, -2], [2]] :=
  checkEncoded_sound gen_gen_20260913_00159

#print axioms gen_gen_20260913_00159_solvable
