import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00158 :
    checkEncoded [[-1], [2]]
      [12, 0, 12, 6, 14, 14, 14, 14, 151, 103, 104, 152, 18, 15, 17, 16, 14, 14, 14, 14, 14, 14, 214, 71, 136, 102, 107, 202, 65, 23, 197, 198, 23, 66, 201, 108, 101, 135, 72, 213, 16, 20, 17, 15, 16, 15, 14, 14, 14, 14, 14, 217, 116, 43, 172, 75, 15, 60, 153, 30, 99, 200, 18, 16, 17, 16, 14, 14, 14, 14, 14, 14, 122, 228, 230, 161, 162, 229, 227, 121, 17, 19, 17, 15, 15, 15, 14, 165, 166, 29, 161, 166, 29, 16, 3, 12, 11, 3, 12, 13, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00158_solvable : EncodedStableSolvable [[-1], [2]] :=
  checkEncoded_sound gen_gen_20260913_00158

#print axioms gen_gen_20260913_00158_solvable
