import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00374 :
    checkEncoded [[-2, 1, 2], [-1, -1, 2, 1, 1]]
      [10, 8, 10, 9, 12, 12, 13, 11, 0, 3, 2, 0, 10, 12, 13, 13, 8, 14, 14, 14, 2, 56, 32, 201, 3, 5, 139, 140, 4, 2, 202, 31, 55, 3, 17, 18, 17, 14, 14, 14, 14, 14, 27, 230, 64, 10, 162, 67, 209, 50, 19, 47, 194, 68, 161, 11, 61, 213, 26, 15, 19, 18, 17, 14, 56, 55, 5, 56, 41, 55, 56, 42, 55, 4, 56, 55, 17, 14, 14, 14, 14, 14, 14, 0, 87, 38, 135, 7, 134, 46, 17, 43, 117, 6, 120, 35, 72, 0, 21, 17, 15, 18, 16, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00374_solvable : EncodedStableSolvable [[-2, 1, 2], [-1, -1, 2, 1, 1]] :=
  checkEncoded_sound gen_gen_20260913_00374

#print axioms gen_gen_20260913_00374_solvable
