import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00136 :
    checkEncoded [[1, -2, 1, 2, -1], [2, 2, -1, -2, -1]]
      [7, 9, 13, 8, 4, 13, 4, 8, 4, 1, 4, 1, 13, 13, 12, 12, 1, 5, 1, 5, 14, 14, 14, 14, 13, 20, 12, 18, 15, 16, 14, 14, 14, 14, 14, 14, 4, 1, 97, 164, 3, 209, 124, 23, 18, 23, 109, 194, 2, 163, 84, 1, 5, 15, 20, 17, 18, 15, 14, 14, 14, 14, 14, 55, 206, 218, 209, 211, 54, 18, 53, 196, 194, 199, 187, 56, 15, 18, 16, 17, 14, 14, 14, 14, 14, 214, 7, 114, 16, 97, 6, 195, 19, 18, 15, 17, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00136_solvable : EncodedStableSolvable [[1, -2, 1, 2, -1], [2, 2, -1, -2, -1]] :=
  checkEncoded_sound gen_gen_20260913_00136

#print axioms gen_gen_20260913_00136_solvable
