import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00031 :
    checkEncoded [[2, -1, 2, 1, -2, 1, -2], [-1, 2, -1, 2, 1, -2, 1]]
      [9, 6, 0, 10, 13, 10, 2, 0, 2, 14, 14, 14, 14, 156, 86, 26, 84, 197, 61, 1, 1, 62, 198, 83, 26, 85, 155, 18, 15, 18, 17, 14, 14, 14, 14, 14, 14, 1, 133, 195, 104, 88, 133, 134, 17, 117, 118, 71, 87, 180, 118, 1, 16, 19, 16, 15, 17, 14, 14, 14, 14, 14, 14, 215, 16, 198, 18, 20, 17, 17, 17, 13, 3, 6, 10, 13, 7, 5, 4, 6, 12, 11, 7, 2, 12, 14, 14, 14, 14, 180, 84, 15, 67, 161, 15, 16, 16, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00031_solvable : EncodedStableSolvable [[2, -1, 2, 1, -2, 1, -2], [-1, 2, -1, 2, 1, -2, 1]] :=
  checkEncoded_sound gen_gen_20260913_00031

#print axioms gen_gen_20260913_00031_solvable
