import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00354 :
    checkEncoded [[-1, 2, 1, -2, 1], [-2]]
      [2, 10, 1, 6, 2, 9, 11, 4, 1, 4, 13, 12, 5, 4, 13, 12, 5, 1, 5, 14, 14, 14, 14, 14, 182, 169, 96, 194, 193, 95, 170, 181, 18, 20, 18, 17, 15, 14, 14, 14, 14, 14, 14, 76, 21, 75, 15, 15, 19, 17, 17, 14, 14, 14, 14, 14, 14, 47, 164, 11, 246, 7, 21, 6, 229, 10, 163, 48, 18, 17, 17, 15, 17, 14, 14, 178, 178, 180, 43, 167, 7, 12, 5, 4, 13, 6, 168, 44, 179, 177, 177, 17, 15, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00354_solvable : EncodedStableSolvable [[-1, 2, 1, -2, 1], [-2]] :=
  checkEncoded_sound gen_gen_20260913_00354

#print axioms gen_gen_20260913_00354_solvable
