import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00254 :
    checkEncoded [[1], [2]]
      [13, 14, 14, 14, 71, 201, 45, 44, 200, 42, 200, 15, 181, 2, 181, 29, 32, 184, 56, 16, 17, 14, 14, 14, 14, 14, 14, 147, 82, 129, 256, 186, 156, 247, 17, 230, 153, 167, 237, 114, 67, 146, 16, 16, 18, 15, 16, 14, 14, 14, 14, 56, 88, 57, 151, 60, 71, 177, 20, 178, 72, 59, 152, 58, 87, 55, 16, 16, 17, 14, 12, 6, 4, 5, 6, 9, 17, 8, 7, 4, 5, 7, 13, 4, 8, 3, 11, 10, 3, 11, 10, 2, 11, 10, 2, 9, 5, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00254_solvable : EncodedStableSolvable [[1], [2]] :=
  checkEncoded_sound gen_gen_20260913_00254

#print axioms gen_gen_20260913_00254_solvable
