import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00263 :
    checkEncoded [[1], [-1, 2, 1, 1]]
      [5, 6, 6, 10, 12, 14, 14, 5, 42, 42, 69, 70, 41, 41, 4, 18, 17, 14, 14, 14, 81, 31, 31, 43, 44, 32, 32, 82, 17, 17, 15, 14, 14, 14, 14, 14, 110, 26, 81, 117, 76, 61, 16, 46, 59, 102, 68, 25, 95, 16, 16, 16, 15, 14, 14, 14, 14, 14, 14, 156, 79, 47, 19, 46, 78, 153, 21, 18, 15, 18, 16, 14, 14, 14, 14, 14, 14, 199, 101, 252, 256, 144, 238, 193, 109, 41, 42, 110, 194, 237, 143, 255, 251, 102, 200, 16, 15, 20, 16, 17, 15, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00263_solvable : EncodedStableSolvable [[1], [-1, 2, 1, 1]] :=
  checkEncoded_sound gen_gen_20260913_00263

#print axioms gen_gen_20260913_00263_solvable
