import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem gen_gen_20260913_00088 :
    checkEncoded [[1], [2]]
      [14, 14, 14, 14, 87, 150, 186, 215, 47, 220, 164, 15, 10, 201, 34, 198, 167, 8, 72, 17, 16, 15, 14, 14, 14, 14, 14, 14, 67, 42, 225, 157, 154, 9, 125, 87, 101, 29, 30, 102, 88, 126, 8, 153, 158, 226, 41, 68, 22, 17, 17, 17, 16, 15, 14, 6, 12, 6, 2, 8, 3, 8, 7, 17, 6, 9, 2, 9, 3, 7, 13, 7, 14, 14, 14, 14, 14, 2, 0, 197, 120, 173, 42, 6, 7, 41, 174, 119, 198, 0, 3, 16, 20, 18, 18, 16, 14, 14, 14, 14, 14, 14, 146, 19, 143, 15, 17, 19, 16, 16, 16, 15] = true := by
  decide +kernel

theorem gen_gen_20260913_00088_solvable : EncodedStableSolvable [[1], [2]] :=
  checkEncoded_sound gen_gen_20260913_00088

#print axioms gen_gen_20260913_00088_solvable
