import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem golden_accept_stable_median_sac_train_0109 :
    checkEncoded [[-1, 2, 2, 2, 2, 2, 2, 2, 1, -2, -2, -2, -2, -2, -2, -2, -2], [1, 2, 2, 2, 2, 2]]
      [6, 2, 9, 9, 9, 9, 11, 1, 4, 8, 2, 8, 2, 0, 4, 0, 8, 2, 0, 4, 4, 4, 3, 4, 3, 10, 16, 15] = true := by
  decide +kernel

theorem golden_accept_stable_median_sac_train_0109_solvable : EncodedStableSolvable [[-1, 2, 2, 2, 2, 2, 2, 2, 1, -2, -2, -2, -2, -2, -2, -2, -2], [1, 2, 2, 2, 2, 2]] :=
  checkEncoded_sound golden_accept_stable_median_sac_train_0109

#print axioms golden_accept_stable_median_sac_train_0109_solvable
