import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem golden_accept_stable_canon_xy :
    checkEncoded [[1], [2]]
      [16, 15] = true := by
  decide +kernel

theorem golden_accept_stable_canon_xy_solvable : EncodedStableSolvable [[1], [2]] :=
  checkEncoded_sound golden_accept_stable_canon_xy

#print axioms golden_accept_stable_canon_xy_solvable
