import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem golden_accept_stable_canon_yx :
    checkEncoded [[2], [1]]
      [15, 15] = true := by
  decide +kernel

theorem golden_accept_stable_canon_yx_solvable : EncodedStableSolvable [[2], [1]] :=
  checkEncoded_sound golden_accept_stable_canon_yx

#print axioms golden_accept_stable_canon_yx_solvable
