import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem golden_accept_stable_rank3_detour :
    checkEncoded [[1], [2]]
      [14, 161, 162, 17, 16, 15] = true := by
  decide +kernel

theorem golden_accept_stable_rank3_detour_solvable : EncodedStableSolvable [[1], [2]] :=
  checkEncoded_sound golden_accept_stable_rank3_detour

#print axioms golden_accept_stable_rank3_detour_solvable
