import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem golden_accept_stable_longest_sac_train_0066 :
    checkEncoded [[-1, 2, 2, 2, 2, 1, -2, -2, -2, -2, -2], [1, 1, 2, -1, -2]]
      [0, 9, 1, 9, 9, 1, 9, 9, 6, 8, 1, 2, 0, 1, 7, 13, 11, 2, 7, 8, 12, 2, 6, 6, 6, 13, 2, 8, 6, 2, 0, 8, 6, 12, 1, 0, 10, 7, 2, 0, 7, 2, 0, 7, 2, 0, 7, 9, 0, 11, 2, 0, 8, 10, 2, 7, 9, 2, 0, 8, 2, 0, 7, 2, 0, 7, 2, 7, 9, 11, 2, 9, 2, 0, 8, 8, 10, 2, 7, 9, 2, 0, 8, 2, 0, 7, 2, 0, 9, 2, 8, 7, 2, 0, 7, 2, 7, 9, 2, 7, 10, 2, 0, 6, 8, 11, 2, 0, 7, 2, 0, 7, 2, 0, 7, 2, 0, 9, 11, 2, 8, 7, 10, 2, 0, 7, 2, 0, 7, 2, 0, 7, 2, 7, 10, 2, 0, 7, 11, 11, 2, 7, 7, 2, 7, 7, 2, 0, 4, 0, 7, 4, 2, 7, 2, 2, 0, 4, 3, 16, 15] = true := by
  decide +kernel

theorem golden_accept_stable_longest_sac_train_0066_solvable : EncodedStableSolvable [[-1, 2, 2, 2, 2, 1, -2, -2, -2, -2, -2], [1, 1, 2, -1, -2]] :=
  checkEncoded_sound golden_accept_stable_longest_sac_train_0066

#print axioms golden_accept_stable_longest_sac_train_0066_solvable
