import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0126 :
    checkEncoded [[-1, 2, 1, -2, -2], [1, 1, 2, 2, -1, -2, -2]]
      [0, 11, 1, 6, 4, 7, 2, 0, 9, 4, 0, 2, 7, 2, 0, 1, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0126_solvable : EncodedStableSolvable [[-1, 2, 1, -2, -2], [1, 1, 2, 2, -1, -2, -2]] :=
  checkEncoded_sound train_ms_train_0126

#print axioms train_ms_train_0126_solvable
