import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0054 :
    checkEncoded [[-1, 2, 1, -2, -2], [1, 2, -1, 2, 1]]
      [9, 11, 1, 13, 8, 4, 0, 9, 9, 13, 2, 0, 6, 2, 0, 4, 11, 4, 4, 3, 4, 3, 10, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0054_solvable : EncodedStableSolvable [[-1, 2, 1, -2, -2], [1, 2, -1, 2, 1]] :=
  checkEncoded_sound train_ms_train_0054

#print axioms train_ms_train_0054_solvable
