import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0207 :
    checkEncoded [[-1, 2, 2, 1, -2, -2, -2], [1, 1, -2, -2, -1, -2, -2]]
      [11, 4, 1, 13, 13, 2, 0, 13, 4, 6, 9, 10, 13, 8, 4, 0, 9, 2, 4, 4, 10, 4, 0, 2, 5, 2, 8, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0207_solvable : EncodedStableSolvable [[-1, 2, 2, 1, -2, -2, -2], [1, 1, -2, -2, -1, -2, -2]] :=
  checkEncoded_sound train_ms_train_0207

#print axioms train_ms_train_0207_solvable
