import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0354 :
    checkEncoded [[-1, 2, 1, -2, -2], [1, 2, -1, -1, 2, 1, 2, 1]]
      [9, 9, 6, 0, 10, 12, 7, 4, 6, 12, 4, 0, 7, 11, 12, 4, 8, 10, 4, 11, 13, 4, 1, 13, 4, 1, 13, 4, 1, 13, 4, 8, 13, 4, 0, 6, 12, 10, 4, 13, 4, 1, 2, 0, 8, 2, 4, 10, 4, 2, 5, 2, 8, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0354_solvable : EncodedStableSolvable [[-1, 2, 1, -2, -2], [1, 2, -1, -1, 2, 1, 2, 1]] :=
  checkEncoded_sound train_ms_train_0354

#print axioms train_ms_train_0354_solvable
