import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0391 :
    checkEncoded [[-1, 2, 2, 2, 1, -2, -2, -2, -2], [1, 2, 2, 1, 2, 2, -1, -2]]
      [0, 9, 1, 13, 8, 6, 9, 9, 12, 2, 7, 9, 2, 1, 13, 11, 12, 4, 1, 7, 11, 0, 9, 1, 9, 13, 13, 2, 9, 9, 2, 12, 12, 10, 4, 1, 2, 0, 7, 9, 9, 2, 0, 8, 13, 2, 6, 2, 12, 10, 4, 0, 6, 8, 10, 4, 1, 2, 0, 7, 9, 4, 1, 2, 13, 4, 1, 2, 0, 7, 2, 2, 0, 4, 10, 4, 2, 5, 2, 8, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0391_solvable : EncodedStableSolvable [[-1, 2, 2, 2, 1, -2, -2, -2, -2], [1, 2, 2, 1, 2, 2, -1, -2]] :=
  checkEncoded_sound train_ms_train_0391

#print axioms train_ms_train_0391_solvable
