import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0160 :
    checkEncoded [[-1, 2, 1, -2, -2], [1, 2, 1, 2, 2, -1, -2]]
      [6, 4, 2, 9, 1, 4, 1, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0160_solvable : EncodedStableSolvable [[-1, 2, 1, -2, -2], [1, 2, 1, 2, 2, -1, -2]] :=
  checkEncoded_sound train_ms_train_0160

#print axioms train_ms_train_0160_solvable
