import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0006 :
    checkEncoded [[-1, 2, 2, 2, 2, 2, 2, 1, -2, -2, -2, -2, -2, -2, -2], [1, 2]]
      [0, 9, 1, 2, 9, 9, 9, 9, 9, 9, 0, 4, 1, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0006_solvable : EncodedStableSolvable [[-1, 2, 2, 2, 2, 2, 2, 1, -2, -2, -2, -2, -2, -2, -2], [1, 2]] :=
  checkEncoded_sound train_ms_train_0006

#print axioms train_ms_train_0006_solvable
