import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0195 :
    checkEncoded [[-1, 2, 1, -2, -2], [1, 2, 2, 2, 2, 2, 2]]
      [0, 9, 1, 9, 6, 8, 4, 13, 4, 13, 4, 13, 4, 1, 2, 0, 7, 9, 4, 0, 2, 6, 2, 2, 1, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0195_solvable : EncodedStableSolvable [[-1, 2, 1, -2, -2], [1, 2, 2, 2, 2, 2, 2]] :=
  checkEncoded_sound train_ms_train_0195

#print axioms train_ms_train_0195_solvable
