import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0118 :
    checkEncoded [[-1, 2, 2, 1, -2, -2, -2], [1, -2, 1, 2, 2, -1, -2]]
      [0, 9, 1, 9, 9, 0, 6, 8, 0, 2, 8, 7, 11, 2, 0, 4, 0, 13, 10, 4, 11, 12, 4, 1, 2, 0, 10, 4, 1, 2, 0, 6, 4, 0, 2, 2, 6, 2, 0, 2, 5, 2, 8, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0118_solvable : EncodedStableSolvable [[-1, 2, 2, 1, -2, -2, -2], [1, -2, 1, 2, 2, -1, -2]] :=
  checkEncoded_sound train_ms_train_0118

#print axioms train_ms_train_0118_solvable
