import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0137 :
    checkEncoded [[-1, 2, 1, -2, -2], [1, -2, 1, 2, -1, -2, -2]]
      [0, 9, 1, 11, 12, 11, 4, 1, 10, 13, 0, 8, 4, 0, 13, 4, 10, 13, 4, 1, 2, 0, 9, 4, 0, 2, 2, 7, 2, 0, 1, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0137_solvable : EncodedStableSolvable [[-1, 2, 1, -2, -2], [1, -2, 1, 2, -1, -2, -2]] :=
  checkEncoded_sound train_ms_train_0137

#print axioms train_ms_train_0137_solvable
