import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0247 :
    checkEncoded [[-1, 2, 1, -2, -2], [1, 2, 1, -2, -1, -2, -2, -2]]
      [9, 11, 13, 4, 1, 8, 6, 13, 9, 10, 13, 0, 7, 13, 11, 4, 12, 12, 4, 1, 8, 8, 13, 4, 12, 12, 4, 12, 12, 4, 0, 10, 13, 1, 2, 0, 6, 2, 0, 4, 11, 4, 4, 2, 0, 4, 3, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0247_solvable : EncodedStableSolvable [[-1, 2, 1, -2, -2], [1, 2, 1, -2, -1, -2, -2, -2]] :=
  checkEncoded_sound train_ms_train_0247

#print axioms train_ms_train_0247_solvable
