import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0398 :
    checkEncoded [[-1, 2, 2, 1, -2, -2, -2], [1, 2, 2, 2, -1, 2, 1, -2]]
      [6, 2, 9, 0, 13, 4, 9, 12, 11, 13, 4, 13, 13, 0, 4, 0, 2, 7, 2, 0, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0398_solvable : EncodedStableSolvable [[-1, 2, 2, 1, -2, -2, -2], [1, 2, 2, 2, -1, 2, 1, -2]] :=
  checkEncoded_sound train_ms_train_0398

#print axioms train_ms_train_0398_solvable
