import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0048 :
    checkEncoded [[-1, 2, 2, 2, 2, 2, 2, 1, -2, -2, -2, -2, -2, -2, -2], [1, 2, 2, 2, 2]]
      [6, 2, 9, 9, 9, 11, 13, 0, 2, 0, 4, 10, 4, 4, 4, 2, 5, 2, 8, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0048_solvable : EncodedStableSolvable [[-1, 2, 2, 2, 2, 2, 2, 1, -2, -2, -2, -2, -2, -2, -2], [1, 2, 2, 2, 2]] :=
  checkEncoded_sound train_ms_train_0048

#print axioms train_ms_train_0048_solvable
