import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0312 :
    checkEncoded [[-1, 2, 2, 2, 1, -2, -2, -2, -2], [1, 2, 2, 2, 2, 2, 2, 2]]
      [6, 2, 0, 9, 4, 0, 1, 9, 9, 4, 0, 13, 4, 1, 2, 9, 2, 9, 2, 9, 2, 0, 4, 0, 9, 2, 0, 4, 4, 4, 2, 5, 2, 8, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0312_solvable : EncodedStableSolvable [[-1, 2, 2, 2, 1, -2, -2, -2, -2], [1, 2, 2, 2, 2, 2, 2, 2]] :=
  checkEncoded_sound train_ms_train_0312

#print axioms train_ms_train_0312_solvable
