import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0143 :
    checkEncoded [[-1, 2, 2, 1, -2, -2, -2], [1, -2, -2, -2, -2, -2, -2]]
      [9, 11, 12, 12, 12, 0, 8, 4, 1, 2, 0, 9, 4, 1, 2, 8, 8, 2, 8, 8, 2, 6, 9, 2, 0, 4, 0, 6, 2, 0, 4, 11, 4, 4, 2, 0, 4, 3, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0143_solvable : EncodedStableSolvable [[-1, 2, 2, 1, -2, -2, -2], [1, -2, -2, -2, -2, -2, -2]] :=
  checkEncoded_sound train_ms_train_0143

#print axioms train_ms_train_0143_solvable
