import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0110 :
    checkEncoded [[-1, 2, 1, -2, -2], [1, 2, -1, 2, 1, -2]]
      [0, 9, 4, 0, 9, 4, 1, 2, 0, 10, 4, 1, 2, 2, 1, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0110_solvable : EncodedStableSolvable [[-1, 2, 1, -2, -2], [1, 2, -1, 2, 1, -2]] :=
  checkEncoded_sound train_ms_train_0110

#print axioms train_ms_train_0110_solvable
