import StableCertificate
open AC.Stable

/-- Generated by tools/kernel_theorems.py. -/
theorem train_ms_train_0245 :
    checkEncoded [[-1, 2, 1, -2, -2], [1, -2, 1, -2, -1, -2, -2, -2]]
      [0, 9, 1, 9, 6, 0, 11, 12, 4, 13, 10, 4, 1, 8, 13, 13, 4, 0, 7, 9, 11, 4, 1, 8, 6, 0, 10, 1, 12, 4, 0, 7, 9, 11, 4, 1, 12, 4, 9, 12, 4, 0, 6, 13, 10, 4, 12, 4, 12, 4, 1, 2, 0, 9, 2, 4, 10, 4, 0, 2, 5, 2, 8, 16, 15] = true := by
  decide +kernel

theorem train_ms_train_0245_solvable : EncodedStableSolvable [[-1, 2, 1, -2, -2], [1, -2, 1, -2, -1, -2, -2, -2]] :=
  checkEncoded_sound train_ms_train_0245

#print axioms train_ms_train_0245_solvable
