#!/usr/bin/env python3
"""Generate lean/StableCertificate/Table.lean from the official stable_move_spec.json.

Never hand-edit Table.lean. Run from the repository root:
    python3 tools/gen_table.py --spec <path to stable_move_spec.json>
The script asserts 257 rows with ids 0..256 in order and refuses unknown fields.
"""
import argparse, hashlib, json, sys

ALLOWED = {
    "inversion": {"id", "category", "relator", "inverse"},
    "multiplication": {"id", "category", "relator", "other", "invert_other", "inverse"},
    "conjugation": {"id", "category", "relator", "conjugator", "inverse"},
    "stabilize": {"id", "category", "inverse"},
    "destabilize": {"id", "category", "relator", "inverse"},
}

def lean_inv(v):
    return "none" if v is None else f"(some {v})"

def row_to_lean(r):
    cat = r["category"]
    assert set(r) == ALLOWED[cat], (r, ALLOWED[cat])
    inv = lean_inv(r["inverse"])
    if cat == "inversion":
        return f"  .inversion {r['relator']} {inv}"
    if cat == "multiplication":
        io = "true" if r["invert_other"] else "false"
        return f"  .multiplication {r['relator']} {r['other']} {io} {inv}"
    if cat == "conjugation":
        c = r["conjugator"]
        return f"  .conjugation {r['relator']} ({c} : Int) {inv}"
    if cat == "stabilize":
        return f"  .stabilize {inv}"
    if cat == "destabilize":
        return f"  .destabilize {r['relator']} {inv}"
    raise AssertionError(cat)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True)
    ap.add_argument("--out", default="lean/StableCertificate/Table.lean")
    a = ap.parse_args()
    raw = open(a.spec, "rb").read()
    spec = json.loads(raw)
    assert spec["move_spec_version"] == "sac-r8-v1", spec["move_spec_version"]
    moves = spec["moves"]
    assert len(moves) == 257, len(moves)
    assert [m["id"] for m in moves] == list(range(257))
    canon = json.dumps(moves, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()
    h = "sha256:" + hashlib.sha256(canon).hexdigest()
    assert h == spec["move_spec_hash"], (h, spec["move_spec_hash"])
    lines = [row_to_lean(m) + ("," if i < 256 else "") for i, m in enumerate(moves)]
    body = "\n".join(lines)
    out = f"""import StableCertificate.Row

/-!
# The frozen `sac-r8-v1` move table

Generated by `tools/gen_table.py` from the official
`competition/tools/verifier/data/stable_move_spec.json`
(move_spec_hash {spec["move_spec_hash"]}).
Do not edit by hand. `StableCertificate.Table.roundTrip` re-serializes the
rows so the test suite can diff them against the specification file.
-/

namespace AC.Stable

/-- The 257 frozen rows, index = move id. Irreducible so that the elaborator never
unfolds the literal during definitional-equality checks; the kernel still evaluates it. -/
@[irreducible] def table : Array Row := #[
{body}
]

theorem table_size : table.size = 257 := by decide +kernel

end AC.Stable
"""
    with open(a.out, "w") as f:
        f.write(out)
    print(f"wrote {a.out}: {len(moves)} rows, hash {h}")

if __name__ == "__main__":
    main()
