"""Kernel-check a selection of certificates as Lean theorems and record timings.

Selection: the six accepted stable golden vectors (including the rank-3 detour),
20 training certificates spread over the length range (including the longest),
and 20 generated certificates that reach rank 3 or more. Each certificate becomes
one theorem `checkEncoded start moves = true := by decide +kernel` in its own file
under lean/Checks/Kernel/, so the wall-clock time per theorem can be measured with
`lake env lean`. A baseline file with no theorem measures import overhead. Every
file also prints its axioms, and the gate is applied to every theorem.
"""
import argparse, json, pathlib, re, subprocess, sys, time
from harness import ROOT, load_verifier, data_path, ledger

ALLOWED = {"propext", "Classical.choice", "Quot.sound"}
LEAN_DIR = ROOT / "lean"
OUT = LEAN_DIR / "Checks" / "Kernel"

def theorem_src(name, start, moves):
    return (f"import StableCertificate\nopen AC.Stable\n\n"
            f"/-- Generated by tools/kernel_theorems.py. -/\n"
            f"theorem {name} :\n    checkEncoded {json.dumps(start)}\n"
            f"      {json.dumps(moves)} = true := by\n  decide +kernel\n\n"
            f"theorem {name}_solvable : EncodedStableSolvable {json.dumps(start)} :=\n"
            f"  checkEncoded_sound {name}\n\n#print axioms {name}_solvable\n")

def run(path):
    t = time.time()
    r = subprocess.run(["lake", "env", "lean", str(path)], cwd=LEAN_DIR, capture_output=True, text=True)
    return time.time() - t, r

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--generated", default="corpus/generated.jsonl")
    ap.add_argument("--n-training", type=int, default=20)
    ap.add_argument("--n-generated", type=int, default=20)
    a = ap.parse_args()
    root, core, sc = load_verifier()
    gv = json.load(open(data_path(root, "golden_vectors.json")))
    ex = root / "competition" / "examples"
    stable = json.load(open(ex / "stable_training_424.json"))["instances"]
    gen = [json.loads(l) for l in open(a.generated)]
    items = []
    for v in gv["verify_vectors"]:
        ch = gv["challenges"][v["challenge_id"]]
        if ch["move_spec_version"] == "sac-r8-v1" and v["expected"].get("ok"):
            items.append(("golden_" + v["name"].replace("-", "_"), ch["initial_relators"], v["moves"], "golden"))
    st = sorted(stable, key=lambda it: len(it["moves"]))
    idx = sorted(set(round(i * (len(st) - 1) / (a.n_training - 1)) for i in range(a.n_training)))
    for i in idx:
        it = st[i]
        items.append(("train_" + it["training_id"].replace("-", "_"), it["initial_relators"], it["moves"], "training"))
    hi = sorted([g for g in gen if g["max_rank"] >= 3], key=lambda g: (-g["max_rank"], -g["length"]))
    for g in hi[:a.n_generated]:
        items.append(("gen_" + g["challenge_id"].replace("-", "_"), g["initial_relators"], g["moves"], "generated"))
    OUT.mkdir(parents=True, exist_ok=True)
    for f in OUT.glob("*.lean"):
        f.unlink()
    (OUT / "Baseline.lean").write_text("import StableCertificate\nopen AC.Stable\n")
    base_t, r = run(OUT / "Baseline.lean")
    assert r.returncode == 0, r.stderr + r.stdout
    results = []
    all_ok = True
    for name, start, moves, kind in items:
        path = OUT / f"{name}.lean"
        path.write_text(theorem_src(name, start, moves))
        t, r = run(path)
        m = re.search(r"'([^']+)_solvable' depends on axioms: \[(.*)\]", r.stdout)
        axioms = {x.strip() for x in m.group(2).split(",")} if m else None
        ok = r.returncode == 0 and axioms is not None and not (axioms - ALLOWED)
        all_ok = all_ok and ok
        stt = tuple(tuple(w) for w in start); ranks = [len(stt)]
        for mv in moves:
            stt, _ = sc.apply_move(stt, mv); ranks.append(len(stt))
        rec = {"name": name, "kind": kind, "moves": len(moves), "max_rank": max(ranks),
               "wall_s": round(t, 2), "wall_minus_baseline_s": round(t - base_t, 2),
               "axioms": sorted(axioms) if axioms else None, "ok": ok}
        results.append(rec)
        print(f"  {'ok ' if ok else 'FAIL'} {name:40} moves={len(moves):4} rank<={max(ranks)} {t:6.2f}s")
        if not ok:
            print(r.stdout[-2000:], r.stderr[-2000:])
    json.dump({"baseline_s": round(base_t, 2), "results": results}, open("ledger/kernel_timings.json", "w"), indent=1)
    # keep a root file so `lake build Checks` compiles every kernel theorem too
    lines = ["import Checks.Kernel." + p.stem for p in sorted(OUT.glob("*.lean")) if p.stem != "Baseline"]
    (LEAN_DIR / "Checks" / "KernelAll.lean").write_text("\n".join(lines) + "\n")
    ledger("kernel_theorems", all_ok, theorems=len(results), baseline_s=round(base_t, 2),
           max_wall_s=max(r["wall_s"] for r in results), total_wall_s=round(sum(r["wall_s"] for r in results), 1),
           by_kind={k: sum(1 for r in results if r["kind"] == k) for k in ("golden", "training", "generated")},
           max_moves=max(r["moves"] for r in results), max_rank=max(r["max_rank"] for r in results))
    sys.exit(0 if all_ok else 1)

if __name__ == "__main__":
    main()
