import StableCertificate.NormalClosure

/-!
# Conjecture 19 of Shehper et al., stated and reduced

Conjecture 19 (arXiv:2408.15332v2): let `⟨x₁,…,xₙ | r₁,…,rₙ₋₁⟩` present ℤ with every
generator generating it, i.e. `x_i = x_j^{±1}` in the group; then for every word `w`
of exponent sum ±1 the balanced presentation `⟨x | r, w⟩` is AC-trivial. This module
states the conjecture against the official definitions, with the relators indexed
by `Fin n` and slot `i` holding `w`, and proves that it reduces to the single case
`w = x_i`: under the generator hypothesis alone, if `⟨x | r, x_i⟩` is AC-trivial then
so is `⟨x | r, w⟩` for every `w` of signed exponent sum ±1. The exponent sum is
weighted by the signs `ε j` with which `x_j ≡ x_i^{ε j}`; when all signs are `+1` it
is the ordinary exponent sum, as in the Wirtinger case. Nothing beyond this
reduction is claimed.
-/

namespace AC

open Subgroup

variable {n : ℕ}

/-- The signed exponent sum: the homomorphism to `Multiplicative ℤ` sending `x_j` to `ε j`. -/
def signedSum (ε : Fin n → ℤ) : Word n →* Multiplicative ℤ :=
  FreeGroup.lift fun j => Multiplicative.ofAdd (ε j)

/-- The ordinary exponent sum is the signed sum with every sign `+1`. -/
def exponentSum : Word n →* Multiplicative ℤ := signedSum fun _ => 1

@[simp] theorem signedSum_of (ε : Fin n → ℤ) (j : Fin n) :
    signedSum ε (FreeGroup.of j) = Multiplicative.ofAdd (ε j) := by
  simp [signedSum]

/-- The homomorphism `k ↦ x ^ k` from `Multiplicative ℤ`. -/
def zpowHom {G : Type*} [Group G] (x : G) : Multiplicative ℤ →* G where
  toFun k := x ^ Multiplicative.toAdd k
  map_one' := by simp
  map_mul' a b := by simp [zpow_add]

@[simp] theorem zpowHom_apply {G : Type*} [Group G] (x : G) (k : Multiplicative ℤ) :
    zpowHom x k = x ^ Multiplicative.toAdd k := rfl

/-- Every generator `x_j` is congruent to `x_i^{ε j}` with `ε j = ±1` modulo the
relators other than `i`. -/
structure GeneratorsCongruent (R : Relators n) (i : Fin n) (ε : Fin n → ℤ) : Prop where
  sign : ∀ j, ε j = 1 ∨ ε j = -1
  congr : ∀ j, (FreeGroup.of j)⁻¹ * (FreeGroup.of i) ^ (ε j) ∈ normalClosure (others R i)

/-- `x_i` has infinite order modulo the relators other than `i`; together with
`GeneratorsCongruent` this says those relators present ℤ generated by `x_i`. -/
def InfiniteOrderMod (R : Relators n) (i : Fin n) : Prop :=
  ∀ k : ℤ, (FreeGroup.of i) ^ k ∈ normalClosure (others R i) → k = 0

/-- Under the generator hypothesis, every word is congruent to `x_i` raised to its
signed exponent sum: the two homomorphisms into the quotient agree on generators. -/
theorem GeneratorsCongruent.congr_all {R : Relators n} {i : Fin n} {ε : Fin n → ℤ}
    (h : GeneratorsCongruent R i ε) (w : Word n) :
    w⁻¹ * (FreeGroup.of i) ^ (Multiplicative.toAdd (signedSum ε w)) ∈
      normalClosure (others R i) := by
  set N := normalClosure (others R i) with hN
  let ψ : Word n →* Word n ⧸ N := QuotientGroup.mk' N
  let χ : Word n →* Word n ⧸ N := (zpowHom (ψ (FreeGroup.of i))).comp (signedSum ε)
  have hgen : ∀ j, ψ (FreeGroup.of j) = χ (FreeGroup.of j) := by
    intro j
    simp only [χ, MonoidHom.comp_apply, signedSum_of, zpowHom_apply, toAdd_ofAdd]
    rw [← map_zpow]
    simp only [ψ, QuotientGroup.mk'_apply]
    exact QuotientGroup.eq.mpr (h.congr j)
  have hψχ : ψ = χ := FreeGroup.ext_hom ψ χ hgen
  have hw := DFunLike.congr_fun hψχ w
  simp only [χ, MonoidHom.comp_apply, zpowHom_apply] at hw
  rw [← map_zpow] at hw
  simp only [ψ, QuotientGroup.mk'_apply] at hw
  exact QuotientGroup.eq.mp hw

/-- Conjecture 19 of Shehper et al., against the official definitions. -/
def Conjecture19 : Prop :=
  ∀ (n : ℕ) (R : Relators n) (i : Fin n) (ε : Fin n → ℤ),
    GeneratorsCongruent R i ε → InfiniteOrderMod R i →
    ∀ w : Word n, (Multiplicative.toAdd (signedSum ε w) = 1 ∨
        Multiplicative.toAdd (signedSum ε w) = -1) →
      Reachable (Function.update R i w) (standard n)

/-- The reduction: under the generator hypothesis, the case `w = x_i` implies every case. -/
theorem conjecture19_reduction {R : Relators n} {i : Fin n} {ε : Fin n → ℤ}
    (h : GeneratorsCongruent R i ε)
    (hstd : Reachable (Function.update R i (FreeGroup.of i)) (standard n))
    (w : Word n)
    (hw : Multiplicative.toAdd (signedSum ε w) = 1 ∨ Multiplicative.toAdd (signedSum ε w) = -1) :
    Reachable (Function.update R i w) (standard n) := by
  apply Reachable.standard_of_congr_generator (Function.update R i w) i i _ hw
  · rw [Function.update_self, others_update]; exact h.congr_all w
  · rw [Function.update_idem]; exact hstd

/-- Conjecture 19 is equivalent to its special case `w = x_i`. -/
theorem conjecture19_iff_generator :
    Conjecture19 ↔ ∀ (n : ℕ) (R : Relators n) (i : Fin n) (ε : Fin n → ℤ),
      GeneratorsCongruent R i ε → InfiniteOrderMod R i →
      Reachable (Function.update R i (FreeGroup.of i)) (standard n) := by
  constructor
  · intro hc n R i ε h hz
    refine hc n R i ε h hz (FreeGroup.of i) ?_
    simpa using h.sign i
  · intro hc n R i ε h hz w hw
    exact conjecture19_reduction h (hc n R i ε h hz) w hw

end AC
